name: Build and publish dotnet packages

on:
  push:
    paths:
      - 'src/core-packages/dotnet/packs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
        source-url: https://nuget.pkg.github.com/culaja/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build solution and generate NuGet packages
      run: |
        cd src/core-packages/dotnet/Packs
        dotnet pack -c Release -o out 
    - name: Push generated packages to GitHub registry
      run: dotnet nuget push './src/core-packages/dotnet/packs/out/*.nupkg' --skip-duplicate --no-symbols true
