name: Build and publish base docker images

on:
  push:
    paths:
      - 'src/core-packages/docker/**'
  create:
    tags:
      - '**'

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build base docker images
      run: |
        bash .github/supportive-scripts/resolve-version-tags.sh src/core-packages/docker/build.env ${GITHUB_SHA}
        docker-compose -f src/core-packages/docker/docker-compose.yml --env-file src/core-packages/docker/build.env build
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish base docker images
      run: |
        cd ./src/core-packages/docker/
        docker-compose --env-file build.env push
